### PR TITLE
downsync

### PR DESCRIPTION
**Pull request by nicechester**

### CODE REVIEW

**Comment by nicechester** [comment]
downsync

**Comment by hojel** [comment]
I don't manage source code here & no plan to manage it in public space.
If you give me your account name of bitbucket.org, I give you permission to
access.

**Comment by nicechester** [comment]
No worries.  That was my mistake.
I was meant to downsync from ianhmcleod for my fixes.

**Comment by nicechester** [comment]
My bitbucket account is violkim@gmail.com

**Pull request closed without merging**
